//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_airline_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancellation
    {
        public int cancellation_id { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public System.DateTime cancellation_date { get; set; }
        public decimal cancellation_amount { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
