//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_airline_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passenger
    {
        public int id { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public string Name { get; set; }
        public int age { get; set; }
        public string contact { get; set; }
        public string seatno { get; set; }
        public string email { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
