//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_airline_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_otp
    {
        public int id { get; set; }
        public int otp { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual User_Master User_Master { get; set; }
    }
}
